name: Recovery Build Simplified

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          sudo apt update
          sudo apt install -y abootimg

      - name: Create Output
        run: |
          mkdir output
          # যদি আপনার রিপোজিটরিতে original_dtb.img থাকে
          if [ -f "original_dtb.img" ]; then
            cp original_dtb.img output/
            echo "DTB copied."
          fi
          # টেস্ট হিসেবে বোর্ড কনফিগ কপি করা
          if [ -f "BoardConfig.mk" ]; then
            cp BoardConfig.mk output/
            echo "BoardConfig copied."
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Recovery-Files-For-Infinix
          path: output/*
          
